# Generated by Django 4.1.3 on 2022-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adid', models.TextField()),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alid', models.IntegerField()),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='AlumnoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.IntegerField()),
                ('mensaje_id_mensaje', models.IntegerField()),
            ],
            options={
                'db_table': 'alumno_mensaje',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_audio', models.IntegerField()),
                ('id_explicacion_a', models.IntegerField()),
            ],
            options={
                'db_table': 'audio',
            },
        ),
        migrations.CreateModel(
            name='Explicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_explicacion', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'explicacion',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_imagen', models.IntegerField()),
                ('item_id_item', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.IntegerField()),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mensaje', models.IntegerField()),
                ('titulo', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mensaje',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_menu', models.IntegerField()),
                ('tipo', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tarea_menu_id_tarea', models.TextField()),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_notificacion', models.IntegerField()),
                ('titulo', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Pictograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_picto', models.IntegerField()),
                ('secuencia_pictogramas_id_sec', models.IntegerField()),
            ],
            options={
                'db_table': 'pictograma',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plato', models.IntegerField()),
                ('tipo_plato', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_id_imagen', models.TextField(unique=True)),
                ('menu_id_menu', models.TextField()),
            ],
            options={
                'db_table': 'plato',
            },
        ),
        migrations.CreateModel(
            name='ProfeMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_id', models.IntegerField()),
                ('mensaje_id_mensaje', models.IntegerField()),
            ],
            options={
                'db_table': 'profe_men',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proid', models.TextField()),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Relation10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_id_imagen', models.IntegerField()),
                ('explicacion_id_explicacion', models.IntegerField()),
            ],
            options={
                'db_table': 'relation_10',
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_retroalimentacion', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tarea_id_tarea', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'retroalimentacion',
            },
        ),
        migrations.CreateModel(
            name='SecuenciaPictogramas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sec', models.IntegerField()),
                ('orden', models.TextField(blank=True, null=True)),
                ('explicacion_id_explicacion', models.IntegerField()),
            ],
            options={
                'db_table': 'secuencia_pictogramas',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.IntegerField()),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
        migrations.CreateModel(
            name='TareaComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.TextField()),
            ],
            options={
                'db_table': 'tarea_comanda',
            },
        ),
        migrations.CreateModel(
            name='TareaFotocopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.IntegerField()),
                ('aula', models.TextField(blank=True, null=True)),
                ('cantidad', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea_fotocopia',
            },
        ),
        migrations.CreateModel(
            name='TareaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.IntegerField()),
                ('aula', models.TextField(blank=True, null=True)),
                ('cantidad_requerida', models.TextField(blank=True, null=True)),
                ('cantidad_conseguida', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea_material',
            },
        ),
        migrations.CreateModel(
            name='TareamatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_item', models.IntegerField()),
                ('tarea_material_id_tarea', models.IntegerField()),
            ],
            options={
                'db_table': 'tareamat_item',
            },
        ),
        migrations.CreateModel(
            name='TareaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.TextField()),
                ('aula', models.TextField(blank=True, null=True)),
                ('cantidad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea_menu',
            },
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_texto', models.IntegerField()),
                ('explicacion_id_explicacion', models.IntegerField()),
            ],
            options={
                'db_table': 'texto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellidos', models.TextField(blank=True, null=True)),
                ('nombre_usuario', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioNotifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('notificacion_id_notificacion', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario_notifi',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('tarea_id_tarea', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario_tarea',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacion_id_explicacion', models.IntegerField()),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
