# Generated by Django 4.1.3 on 2022-12-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idta', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('corregido', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idus', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellidos', models.TextField(blank=True, null=True)),
                ('nombre_usuario', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.usuario')),
                ('aula', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumno',
            },
            bases=('apiApp.usuario',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.usuario')),
                ('es_admin', models.BooleanField()),
            ],
            options={
                'db_table': 'profesor',
            },
            bases=('apiApp.usuario',),
        ),
        migrations.CreateModel(
            name='TareaComanda',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.tarea')),
            ],
            options={
                'db_table': 'tarea_comanda',
            },
            bases=('apiApp.tarea',),
        ),
        migrations.CreateModel(
            name='TareaFotocopia',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.tarea')),
                ('aula', models.TextField(blank=True, null=True)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea_fotocopia',
            },
            bases=('apiApp.tarea',),
        ),
        migrations.CreateModel(
            name='TareaMaterial',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.tarea')),
                ('aula', models.TextField(blank=True, null=True)),
                ('cantidad_requerida', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_conseguida', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea_material',
            },
            bases=('apiApp.tarea',),
        ),
        migrations.CreateModel(
            name='TareaMenu',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.tarea')),
                ('aula', models.TextField(blank=True, null=True)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea_menu',
            },
            bases=('apiApp.tarea',),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.usuario'),
        ),
        migrations.CreateModel(
            name='Pictograma',
            fields=[
                ('id_picto', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.TextField()),
                ('secuencia', models.IntegerField(null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.tarea')),
            ],
            options={
                'db_table': 'pictograma',
            },
        ),
    ]
