# Generated by Django 4.1.3 on 2022-11-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idus',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
